### ISSUE TITLE
Run local integration tests

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#13]
## Is your feature request related to a problem? Please describe
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
When modifying the codebase and wanting to verify the package through both integration and unit tests, the integration tests never succeed for me. I have the environment variables configured and I'm running VS as an administrator although the PowerShell script ran as a part of the test fixture always falls over. 

I believe this is to do with either not being admin (although this shouldn't be the case) OR the execution policy.

## Describe the solution you'd like
_A clear and concise description of what you want to happen._
Not sure yet - something to discuss and experiment with.

**Comment by ewingjm** [comment]
Hey, @tdashworth. Can this one be closed now? I think we established that this was a case of needing to set the execution policy _as_ an admin? Unless we want it to be documented in the CONTRIBUTING.md rather than just in this issue.

**Comment by tdashworth** [comment]
I am still facing the issue although it seems you and @markcunninghamuk have it working. Think some contribution guidance would be helpful.

**Comment by tdashworth** [comment]
I've just checked them again this morning and it worked fine on [11f0c1a1](https://github.com/Capgemini/powerapps-packagedeployer-template/commit/11f0c1a11741cf49fd68e460a8b3e3ff96842d67). Closing issue.
