### ISSUE TITLE
Workflows Activation and Deactivation does not work for multiple workflows

### ISSUE THREAD

**Issue by ksulikow** [Capgemini/powerapps-packagedeployer-template#21]
## Describe the bug
When you add more items in this section then it fails with an error

## To reproduce

Add more than one workflow in the config file eg:
  <processestodeactivate>
    <processtodeactivate>Process name 1</processtodeactivate>
    <processtodeactivate>Process name 2</processtodeactivate>
  </processestodeactivate>
or
  <processestoactivate>
    <processtoactivate>Process name 1</processtoactivate>
    <processtoactivate>Process name 2</processtoactivate>
  </processestoactivate>

and you will get an exception - there is a bug in this.QueryWorkflowsByName method used in both above scenarios

## Expected behaviour
Expected behavior is to get all the workflows Activated or Deactivated, depends what section it is.

## Screenshots
None

## Environment (please complete the following information):
 - Version Latest
 - Power Apps environment version

## Additional context
None

**Comment by tdashworth** [comment]
Hi @ksulikow, I'm not seeing a difference between those two examples. Also, do you have a copy of the exception being thrown? 

It doesn't look like we have a test for this so I'll first try to replicate the issue.

**Comment by ewingjm** [comment]
From memory, I think `QueryByAttribute` expects the same number of `Attributes` as it does `Values`. Might have been my mistake in assuming adding a range of values does something along the lines of `ConditionOperator.In`! We'll probably just need to change this to a `QueryExpression`.
