### ISSUE TITLE
Remove/disable Wiki

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#23]
The [wiki here on GitHub](https://github.com/Capgemini/powerapps-packagedeployer-template/wiki) has become outdated and replaced by a comprehensive README. I believe the wiki should be disabled and removed to avoid confusion leaving one source of truth.

This issue is to discuss this matter before making the settings change. 

I will complete the action if there are no objections on 31st Jan (a week from now).

**Comment by tdashworth** [comment]
No objections so removing the Wiki.

cc: @ewingjm, @markcunninghamuk, @ksulikow

**Comment by ewingjm** [comment]
![Nooo](https://media.giphy.com/media/l0HlDHQEiIdY3kxlm/giphy.gif)

**Comment by tdashworth** [comment]
I have kept a local copy should we need it. Now removed from repo.
