### ISSUE TITLE
Inconsistent logic to handle Flows, Workflows and Plugin SDK steps Activation/DeActivation

### ISSUE THREAD

**Issue by ksulikow** [Capgemini/powerapps-packagedeployer-template#24]
## Describe the bug
Flows will work on solution level - recommended for the others

## Expected behaviour
As Flows are currently implemented

**Comment by ewingjm** [comment]
Flows currently attempt to activate every flow that was found in the deployed solutions **except** the ones that are explicitly called out to be deactivated (which are explicitly updated to inactive). This same logic will need to be implemented for processes and SDK steps. Recommend to do it at the same time as #27.
