### ISSUE TITLE
Use the new Hooks in package deployer to aid upgrade process

### ISSUE THREAD

**Issue by markcunninghamuk** [Capgemini/powerapps-packagedeployer-template#25]
## Is your feature request related to a problem? Please describe
We used to write custom logic and steps because we did not have the lifecycle hooks to aid when upgrading solutions.

**Comment by ewingjm** [comment]
@markcunninghamuk shall we close this one in favour of #30? I think it's referring to the workaround that can implement to fix that one.

**Comment by markcunninghamuk** [comment]
Yes please

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
