### ISSUE TITLE
Feature flag to activate processes for the solutions being deployed

### ISSUE THREAD

**Issue by markcunninghamuk** [Capgemini/powerapps-packagedeployer-template#27]
## Is your feature request related to a problem? Please describe
Would be useful to be able to disable processes for the entire entire environment as well as the processes for the solutions being deployed. It cannot be assumed you want to turn off all processes as you may break another solutions behaviour.

**Comment by tdashworth** [comment]
Would it be worth caching the statuses for when activating? If a process was disabled and outside the package solutions, we might not want it to be activated when activating "all" processes.

**Comment by markcunninghamuk** [comment]
Yes excellent point

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ewingjm** [comment]
This one will probably be done at the same time as #24.

**Comment by ewingjm** [comment]
@markcunninghamuk  @tdashworth is this resolved by #31?

**Comment by tdashworth** [comment]
Deactivating **_ALL_** workflows in an environment is a dangerous operation. If this is something your deployment needs, you are welcome to implement it yourself or use our config to selectively activate/deactivate processes ([Set process states](https://github.com/Capgemini/powerapps-packagedeployer-template#Set-process-states)). 

If you desire this for only the data import, take a look at the data migrator for a similar feature ([Import Config](https://github.com/Capgemini/xrm-datamigration/wiki/Config#import-config) specifically `DeactivateAllProcesses`).
