### ISSUE TITLE
Semantic versioning support for stage for upgrade

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#4]
## Is your feature request related to a problem? Please describe
Using `stage for upgrade` adds significant overhead to deployment times which could be reduced for deployments where it's unnecessary.

## Describe the solution you'd like
A solution could be to only use `stage for upgrade` on solutions where the major version has changed (i.e. breaking changes have been introduced) while using a standard `upgrade`.

## Additional context
- https://semver.org/
- https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/update-solutions#apply-the-upgrade-or-update-in-the-target-environment

**Comment by ewingjm** [comment]
As per my comment on #11, I don't think this is possible.

**Comment by ewingjm** [comment]
Closing based on the above.
