### ISSUE TITLE
Set auto-number seed values

### ISSUE THREAD

**Issue by ewingjm** [Capgemini/powerapps-packagedeployer-template#44]
## Is your feature request related to a problem? Please describe
Setting auto-number seed values is currently a manual process. It would be preferable to have the required seeds passed at run-time for each environment.

## Describe the solution you'd like
Something similar to setting connections. Possibly register auto-number entities and fields within the config file and optionally pass the seed values for these at run-time.

**Comment by mjahlv** [comment]
@ewingjm I'm making a start on this. Here's a summary of what I plan to do:

- Add config (AutonumberSeedConfig.cs) specifying XML attributes for setting Autonumber Seed Values
    - Attributes: Entity name, Autonumber Attribute Name, Attribute Seed Value
- Update Template Config with autonumber config
     - Add XML array AutonumberSeeds with items AutonumberSeed
- Add method for setting Autonumber Seed Values to CrmServiceAdapter.cs (if needed)
- Add a service for setting Autonumber Seed Values called AutonumberSeedSettingService
    - Creates a list of SetAutonumberSeedRequests
    - Calls upon the CRM Service to execute the logic
- Call the Service in AfterPrimaryImport()  of PackageTemplateBase.cs
- Unit test the AutonumberSeedSettingService
- Create an integration test that will check the seed number is set to what is intended
- Update ReadMe.md with Autonumber Seed Config details.

Related Microsoft documentation: https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/create-auto-number-attributes

**Comment by ewingjm** [comment]
Great, @mjahlv. That's all looking good to me. @tdashworth any comments? I wonder if it would be worth structuring the XML schema for the auto-number config to be a little more extensible (comparison below).

```xml
<templateconfig>
  <autonumberseeds>
    <autonumberseed entity="contact" logicalname="new_autonumber" seed="1000" />
  </autonumberseeds>
</templateconfig>
```

```xml
<templateconfig>
  <entities>
    <entity name="contact">
      <field name="new_autonumber" seed="1000" />
    </entity>
  </entities>
</templateconfig>
```

**Comment by mjahlv** [comment]
That approach would be cleaner. I assume then we'd create a config class for entity attributes config (as opposed to just autnoumer seed config) and then the logic would check for if the seed has been populated to determine if we need to be setting an auto-number seed?

**Comment by ewingjm** [comment]
Yup, that's what I'm thinking. I know it made sense for the SDK steps and processes. I guess it just means if we add any more functionality relating to tables or columns (trying to get used to the new terminology 😄) then it might be easier to add in and may reduce some duplication.

**Comment by tdashworth** [comment]
@mjahlv Your plan sounds great - thanks for the contribution. @ewingjm, I agree with the approach for the config - I'm not sure what else we could add but better to have it than not! 😄

**Comment by mjahlv** [comment]
@ewingjm agreed, and it covers us if they add more fields with specialist functionality that we need to care about in the future.

**Comment by tdashworth** [comment]
@mjahlv how are you getting on with this? I would love to use this on my current project 😄

**Comment by mjahlv** [comment]
@tdashworth I've done the work, just need to write and run tests. I'm on leave this week so will pick it up on Monday

**Comment by tdashworth** [comment]
@mjahlv No worries, thanks for the update 😄
