### ISSUE TITLE
Individual warnings and errors are not logged properly to Azure DevOps

### ISSUE THREAD

**Issue by ewingjm** [Capgemini/powerapps-packagedeployer-template#45]
## Describe the bug
The final deploy task status is correctly reported (this is using `Console.WriteLine` to log the command) but individual errors and warnings are not logged properly. I believe this is because they appear in the middle of the string (see screenshot)

## To reproduce
Perform a deployment on Azure DevOps with warnings or errors. Note that, when you open the job, the warnings and errors are not individually broken down as expected.

## Expected behaviour
We should see a count and a breakdown of each warning and error.

## Screenshots
![image](https://user-images.githubusercontent.com/34515225/110511223-97cddc00-8136-11eb-9445-1c459bf03f42.png)

## Additional context
Should probably switch to `Console.WriteLine` as per the working logging command that reports the final task status.

**Comment by tdashworth** [comment]
@ewingjm is this the `TraceLogger` prefixing the line?

**Comment by ewingjm** [comment]
> @ewingjm is this the `TraceLogger` prefixing the line?

Yep, that's why I think the only way around it is to bypass it completely and just go for a `Console.WriteLine`. I did run a few tests on Azure DevOps before I did that PR to check if logging commands in the middle of a line would work. It looked like it did, but it seems not.

**Comment by tdashworth** [comment]
> > @ewingjm is this the `TraceLogger` prefixing the line?
> 
> Yep, that's why I think the only way around it is to bypass it completely and just go for a `Console.WriteLine`. I did run a few tests on Azure DevOps before I did that PR to check if logging commands in the middle of a line would work. It looked like it did, but it seems not.

No worries. What do the ADO docs say? 

I am thinking instead of extending `TraceLogger`, we implement another `ILogger` which uses the `Console`?

**Comment by tdashworth** [comment]
@ewingjm Ahhh okay! That should be an easy fix then 😄
