### ISSUE TITLE
Set Flow connections and activate on deployment

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#5]
## Is your feature request related to a problem? Please describe
With Workflows, we're able to activate them post-deployment. With Flows, this isn't possible as the Connection must be set before activation.

## Describe the solution you'd like
Given Connection references are provided, after deployment the Flows are updated with the references and activated creating a non-interactive deployment.

**Comment by tdashworth** [comment]
@ewingjm I believe you have a working solution for this. May I assign this to you?

**Comment by ewingjm** [comment]
There's some code in the package template for [development-hub](https://github.com/ewingjm/development-hub) that might be useful for this. I suggest we do something like the following - 

1. Retrieve all flows that have just been deployed
2. Get a list of the APIs that are being used (e.g. shared_visualstudioteamservices)
3. Attempt to retrieve the connection names from either `RuntimeSettings` or environment variables using a fixed format (e.g. `PACKAGEDEPLOYER_CONNECTIONNAME_{API NAME}`
4. Set the connection names in the retrieved flows
5. Activate the flows

There is potentially an issue in the order that we activate the flows. I believe any child flows will need to be activated in advance of any flows that call them. I worked around this issue in the Development Hub's package template by handling the order of activation myself.

**Comment by tdashworth** [comment]
Hey @markcunninghamuk, please share your thoughts here for us all to discuss 🙂

**Comment by markcunninghamuk** [comment]
Hey Guys, Here is how I think this will be implemented: In the config I have added something like this. The import config will have this as a new section.
```xml

 <flowconnections>
      <flow useReleaseVariable="true" flowConnectionName="servicebus_example" activateFlow="true" environmentVariableName="MyVariable1"></flow>
 </flowconnections>
```

We retrieve the flow by the name, (We can use the Guid also). For each flow we have here we check if activateFlow = true then we set the connection up. I don't see why we would want to set it up and not have it activated. Then we have the variable attribute to read from either an environment variable in Dynamics (If it allows us to) or the variable from the release pipeline that could be tokenised potentially. In terms of flow we would expect them to order them properly as we wont know which flows are dependent without extra code.

**Comment by ewingjm** [comment]
As you say, I think it's going to be extremely rare that we won't want a flow active after deployment. Maybe we check for `activateFlow="false"` instead and activate them by default (in the interests of making the configuration less verbose). Similarly, I think having an option to explicitly set the environment variable/runtime setting is useful, but we should also have a convention for this so we don't need to explicitly set it each time. The order is probably a good bet to start with, but a retry mechanism where we perform multiple passes would also help.

**Comment by tdashworth** [comment]
#15 only covers the activation - reopening for the setting of connection to be completed.
