### ISSUE TITLE
Option to configure if post deployment steps should run always or not

### ISSUE THREAD

**Issue by ksulikow** [Capgemini/powerapps-packagedeployer-template#57]
At this moment it is a bit inconsistent, some post deployment steps always run, some only when solution was imported. Eg. Data packages are loaded regardless, even when solution is already in the system so does not need to be redeployed, data load runs, but flows activation only runs when solution import was happening.

There should be an option to always run the post deployment steps as it is common DevOps scenario to just run it even when no solutions is imported to eliminate so called infrastructure/configuration drifts - it means manual changes done by someone in controlled env, eg someone stopped a workflow, or changed data we manage - it should not be allowed, and we want to fix it so env matches code.

**Comment by tdashworth** [comment]
What great timing, @ksulikow, I have also noticed this behaviour and been caught out by it.

I think we need to review all post-deployment steps that are affected then consider the options going forward. Do we want global or individual flags to enable this behaviour, for example?

**Comment by ewingjm** [comment]
I don't think there's a need for any additional configuration here - I think this is a straight forward bug fix. The package should be idempotent and it currently isn't. The package should be declaring the desired end state and we should run whatever logic is necessary every time to get it to that state. This means - 

- https://github.com/Capgemini/xrm-datamigration/pull/45 for data imports
- A simple fix for the `ProcessedSolutions` list to include solutions already present in the target environment

I think that's all this is going to take.

**Comment by tdashworth** [comment]
What do you mean by Solution already in the environment? Will is still be scoped to those included in the package?

**Comment by ewingjm** [comment]
Yes. The problem here was the solution was in our package but wasn't deployed because the version was the same. However, we still wanted to activate the flows. We already have a configuration option for processes that aren't in our solutions - they need to be explicitly declared with `external="true"`.
