### ISSUE TITLE
Add option to activate Workflows after ref data deployment

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#6]
## Is your feature request related to a problem? Please describe
In some cases, Workflows and Flows should be disabled during a data import to avoid unnecessary processing and modifications.

## Describe the solution you'd like
Provide the option to select which Workflows/Flows should be disabled during each data import opportunity. These would then be enabled after the import was successful.

**Comment by tdashworth** [comment]
@ksulikow This was originally raised by you in Azure DevOps and I wanted to check the description above fully encompasses the problem you were having.

**Comment by ksulikow** [comment]
It was already implemented by me

**Comment by ksulikow** [comment]
A bug was found that it does not work for more than one workflow in the list, I will try to fix it soon

**Comment by tdashworth** [comment]
Hi @ksulikow, I can't see this implementation. The issue is specifically around controlling which workflows/flows are enabled during the data migration steps. I'm only seeing implementation around the post-deployment data. 

Does that satisfy this issue? If so, please close the issue.

**Comment by ewingjm** [comment]
@ksulikow @tdashworth  I added a missing integration test for this in #22 and added the missing README documentation in #20. Think we can close this one?

**Comment by ewingjm** [comment]
Ah, apologies @tdashworth. I just picked up on what you're saying. The current functionality will potentially leave workflows activate during pre-deployment data import.

**Comment by ewingjm** [comment]
Maybe we trigger some events before and after `DataImporterService.Import" (could possibly even expose these for extensibility) and register the calls to deactivate/activate the workflows on these instead?

**Comment by tdashworth** [comment]
Could we add a `stage` (or multiple) to `ProcessToActivate` and `ProcessToDeactivate` to determine when they should run? Or maybe at the array level. 

Thinking about it, it's probably not a trivial solution...

**Comment by tdashworth** [comment]
> @ksulikow @tdashworth I added the fix and a missing integration test for this in #22 and added the missing README documentation in #20. Think we can close this one?

I think this can be closed now?

**Comment by ewingjm** [comment]
I think the resolution on this one was that you instead specify which workflows you need to be disabled during data import in the data import config .json files as per the capgemini/xrm-datamigration docs.
