### ISSUE TITLE
Documentation Clarifications

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#8]
## Is your feature request related to a problem? Please describe
A couple of questions regarding the package:
- Does this extend Microsoft's Package Deployer? - https://docs.microsoft.com/en-us/power-platform/alm/package-deployer-tool
- Which SLA types do the SLA actions apply to? - https://docs.microsoft.com/en-us/power-platform/admin/enhanced-service-level-agreements#considerations-when-you-choose-a-sla-type

## Describe the solution you'd like
Update the documentation to answer the above questions.

**Comment by ewingjm** [comment]
Hi, @tdashworth. 

- I think it wouldn't be fully accurate to say it's an extension to the Package Deployer as a package template is a requirement for deploying with the Package Deployer - it would be more accurate to say that users extend our package template
- I believe it is enhanced SLAs but I'm not 100% sure

**Comment by tdashworth** [comment]
@ewingjm Do you think we can close this based on the README updates in PR #20?

**Comment by ewingjm** [comment]
Looks like it! I'm not familiar with them but we may need to add some of the new SLA KPIs into the test package and figure out if we need similar functionality to deactivate them before deployments. My gut feeling is that it probably handles it a lot nicer than the old SLAs.

**Comment by tdashworth** [comment]
Agreed but that's for the future 😁. Closing
