### ISSUE TITLE
TraceLoggerAdapter is private within NuGet package

### ISSUE THREAD

**Issue by janis-veinbergs** [Capgemini/powerapps-packagedeployer-template#88]
## Describe the bug
Nuget provided dll has private `TraceLoggerAdapter`. When I look in source code, I see it as protected

I expect to be able to access `TraceLoggerAdapter` within `PackageTemplateBase`

Actually I notice that github, 3 yrs old code even checks `RunninOnAzureDevOps` whereas when I look at provided package .dll from Visual Studio, I don't see that.

But the `packages\capgemini.powerapps.packagedeployertemplate\3.1.3\lib\net462\Capgemini.PowerApps.PackageDeployerTemplate.dll` I have locally has:
```
[assembly: AssemblyInformationalVersion("3.1.3+Branch.master.Sha.a8bae472d34c6c63a6375c671efe0db1f4ac0d8e.a8bae472d34c6c63a6375c671efe0db1f4ac0d8e")]
```

## Screenshots
![image](https://github.com/user-attachments/assets/eec852fa-3da4-4d32-956c-786a09b94102)

## Environment (please complete the following information):
 - Version 3.1.3
 
 ## More
 
 Wow, I'm so confused.
 
 https://www.nuget.org/packages/Capgemini.PowerApps.PackageDeployerTemplate/#versions-body-tab shows latest at 0.3.22
 
 I am 3.1.3 
![image](https://github.com/user-attachments/assets/be87c2cf-e7f5-488b-b3c3-ebece3ee87f3)

The AssemblyInformationalVersion specifies commit a8bae472d34c6c63a6375c671efe0db1f4ac0d8e - a commit made on Feb 1 2021.

**Comment by janis-veinbergs** [comment]
I changed/_downgraded_ to version 0.3.22 and everything is fine. I can access the properties I wanted and it is in line with what I see in source code.

Perhaps initially there were nuget packages published with higher version number than afterwards?

**Comment by ewingjm** [comment]
Hi @janis-veinbergs. 

Apologies for this - I've just had a look and yes, we have a number of unlisted packages starting 3.x.x. 

It's likely because came from the https://www.nuget.org/packages/Capgemini.Xrm.Deployment.PackageDeployer package. We made the decision to reset the version rather than starting at 3.x.x, but we must have already published several 'old' package versions before doing that.
